// Sample data for <kc-artifact>. The docs site serves a real demo artifact from
// public/artifact-demo/ — so the preview iframe frames actual same-origin files
// (styles + relative navigation work, exactly like a hosted artifact) and the
// Code tab shows the same source. `previewHeight` gives the viewer real height.

const base = import.meta.env.BASE_URL.replace(/\/$/, '');
const url = (p: string) => `${base}/artifact-demo/${p}`;

const INDEX_HTML = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="styles.css" />
    <title>Starboard</title>
  </head>
  <body>
    <h1>Starboard</h1>
    <p>A landing page generated by the assistant, framed live in the artifact preview.</p>
    <div class="card">
      <strong>Ship faster</strong>
      <p>Edit the source in the Code tab, or open it in a new browser tab.</p>
    </div>
    <nav><a href="about.html">About →</a></nav>
  </body>
</html>`;

const ABOUT_HTML = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="styles.css" />
    <title>Starboard — About</title>
  </head>
  <body>
    <h1>About Starboard</h1>
    <p>Built with kitn-chat artifacts — a sandboxed preview paired with the source.</p>
    <nav><a href="index.html">← Home</a></nav>
  </body>
</html>`;

const STYLES_CSS = `:root { --accent: #d6207f; --ink: #1b1b1f; --muted: #56565c; }
body {
  font-family: system-ui, sans-serif;
  max-width: 40rem;
  margin: 0 auto;
  padding: 2.5rem 1.5rem;
  color: var(--ink);
  line-height: 1.6;
}
h1 { color: var(--accent); }
a { color: var(--accent); font-weight: 600; }
.card { margin-top: 1.5rem; padding: 1.25rem 1.5rem; border: 1px solid var(--accent); border-radius: 14px; }`;

const FILES = [
  { path: 'index.html', type: 'html', language: 'html', code: INDEX_HTML, url: url('index.html') },
  { path: 'about.html', type: 'html', language: 'html', code: ABOUT_HTML, url: url('about.html') },
  { path: 'styles.css', type: 'other', language: 'css', code: STYLES_CSS, url: url('styles.css') },
];

export default {
  sample: { files: FILES, src: url('index.html'), previewHeight: '440px' },
  named: {
    code: { files: FILES, src: url('index.html'), previewHeight: '440px' },
  },
};
