// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route?: undefined;
    },
    {
      path: "/atelier";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/atelier")>;
      $$route?: undefined;
    },
    {
      path: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route?: undefined;
    },
    {
      path: "/lookbook/:look";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/lookbook/[look]")>;
      $$route?: undefined;
    },
    {
      path: "/lookbook/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/lookbook/index")>;
      $$route?: undefined;
    },
    {
      path: "/shop/:piece";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/shop/[piece]")>;
      $$route?: undefined;
    },
    {
      path: "/shop/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/shop/index")>;
      $$route?: undefined;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/";
      id: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/*404";
      id: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/shop/";
      id: "/shop/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/shop/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/atelier";
      id: "/atelier";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/atelier")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/lookbook/";
      id: "/lookbook/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/lookbook/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/shop/:piece";
      id: "/shop/:piece";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/shop/[piece]")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/lookbook/:look";
      id: "/lookbook/:look";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/lookbook/[look]")>;
      $$route?: undefined;
      children?: undefined;
    }
  ];
}
