// Generates `llms.txt` (curated orientation, llmstxt.org convention) and
// `llms-full.txt` (full per-web-component API reference) for AI coding agents.
//
// Source of truth = the same `elements` model that `gen-web-component-api.mjs` uses
// to write dist/custom-elements.json, so these files can never drift from the
// shipped API. When run standalone (no in-memory import) it falls back to
// reading dist/custom-elements.json.
//
// Outputs (all deterministic — no timestamps/random):
//   - llms.txt              (package root, committed + npm `files`)
//   - llms-full.txt         (package root, committed + npm `files`)
//
// The package-root copies are CANONICAL and the ONLY ones shipped
// (owner-ruled 2026-08-25). A `dist/llms/` copy of each used to ship too —
// ~293 KB of duplicate llms-full weight in every install — and the two copies
// were observed to drift (a stale dist copy without the programmatic markers
// beside a current root copy). The MCP's programmatic-topic slicer reads the
// root copy (mcp/mcp/tools/reference.ts), and `generate()`
// below removes any stale `dist/llms/` left by an earlier build so it cannot
// keep shipping — dist/ is packed wholesale.

import { readFileSync, writeFileSync, rmSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
// The `/state` + `/wire` section, derived from the shipped dist/*.d.ts (F-46).
// A separate module because it parses declarations with the TypeScript API,
// which nothing else in this file needs.
import { buildProgrammaticSection } from './gen-llms-programmatic.mjs';
// The icon roster, derived from the NAMED_ICONS map in src/components/icon/icon.tsx — the
// SAME extraction docs/web-components.md's icon-roster region uses (P-8), so
// the two artifacts cannot disagree about what resolves.
import { iconNames } from './gen-web-components-md.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const toAttr = (name) => name.replace(/([A-Z])/g, '-$1').toLowerCase();
const tagToReact = (tag) =>
  tag.split('-').map((s) => s[0].toUpperCase() + s.slice(1)).join('');
const escapeCell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ').trim();
const isScalarType = (t) =>
  /^(undefined\s*\|\s*)?('[^']*'(\s*\|\s*'[^']*')*|string|number|boolean|true|false)(\s*\|\s*undefined)?$/.test(
    t.replace(/\s+/g, ' ').trim(),
  );

const HEADER_NOTE = '<!-- AUTO-GENERATED by scripts/gen-llms.mjs — do not edit by hand. Run `npm run build`. -->';

// ---------------------------------------------------------------------------
// Curated orientation content (the body of llms.txt). Kept inline so the
// generator owns the canonical copy. `fullOnlyPointers` are the Docs bullets
// derived from FULL_ONLY_SECTIONS below — one per section that exists only in
// llms-full.txt, so llms.txt cannot silently stop indexing one.
// ---------------------------------------------------------------------------
function buildLlmsBody(count, fullOnlyPointers) {
  return `# @kitn.ai/ui

> Framework-agnostic, Shadow-DOM web components for building AI chat interfaces — works in React, Vue, Angular, Svelte, or plain HTML. ${count} custom elements, every one prefixed \`kai-\` (e.g. \`<kai-chat>\`, \`<kai-artifact>\`): streaming responses, markdown + code rendering, reasoning/tool panels, attachments, conversation sidebar, voice input. Zero framework dependency for consumers; the SolidJS runtime it is authored in is bundled in, so the host needs nothing.

## Install

\`\`\`bash
npm install @kitn.ai/ui
# SolidJS consumers also need the peer dep:
npm install solid-js
\`\`\`

## #1 rule: array/object data goes on JS PROPERTIES, not HTML attributes

This is the single most common mistake. Arrays and objects (\`messages\`, \`models\`, \`context\`, \`suggestions\`, \`triggers\`, …) MUST be assigned as JavaScript properties on the element. They CANNOT be passed as HTML attributes — an HTML attribute is always a string and will be ignored or mis-parsed.

\`\`\`js
const chat = document.querySelector('kai-chat');
chat.messages = [{ id: '1', role: 'assistant', parts: [{ type: 'text', text: 'Hi!' }] }]; // ✅ property
\`\`\`
\`\`\`html
<kai-chat messages="[...]"></kai-chat>  <!-- ❌ never works -->
\`\`\`

Only scalar values (string/number/boolean) work as attributes (e.g. \`placeholder\`, \`loading\`, \`theme\`).

## Two layers

**Layer 1 — batteries-included web components** (\`import '@kitn.ai/ui/web-components'\`):
Drop an element into any framework (React, Vue, plain HTML). Data in via JS properties; interactions out via non-bubbling CustomEvents.

- \`<kai-chat>\` — full chat UI (message list + prompt input). The primary starting point.
- \`<kai-conversations>\` — sidebar conversation browser with group support.
- \`<kai-prompt-input>\` — standalone composer with send button.

**Layer 2 — composable custom elements** (\`import { … } from '@kitn.ai/ui'\`):
All ${count} elements are also exported individually. Use them for custom layouts or features \`<kai-chat>\` does not expose (ChainOfThought, FeedbackBar, ThinkingBar, VoiceInput, …). Your bundler tree-shakes the rest.

## Key rules for the web components

1. **Array/object data = JS properties** (see above). Scalars may be attributes.
2. **Events are non-bubbling \`CustomEvent\`s** — listen directly on the element:
   \`chat.addEventListener('kai-submit', (e) => console.log(e.detail.value))\`
3. **\`theme\` attribute** (\`'light' | 'dark' | 'auto'\`) works on every element. Default \`auto\` follows \`prefers-color-scheme\`.
4. **Theming via CSS custom properties** — override \`--kai-color-*\` tokens on \`:root\`; they pierce Shadow DOM.

## ChatMessage schema (required for \`<kai-chat>\`)

A message's content is an **ordered \`parts\` array**. There is no \`content\` string: it was removed in 0.20.0. Text, reasoning, tool calls, generative-UI cards, citations and file attachments all live in \`parts\`, in the order the model produced them, so a post-tool answer renders below its tool panel instead of being glued onto the pre-tool text.

\`\`\`ts
interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  /** The ONLY content channel. Ordered. */
  parts: MessagePart[];
  /** Action buttons under the message. Chrome, not content. */
  actions?: ('copy' | 'like' | 'dislike' | 'regenerate' | 'edit' | 'speak')[];
  avatar?: { src?: string; fallback?: string; alt?: string };
  feedback?: 'like' | 'dislike';
}

/** Six variants, one per kind of content. Every variant may also carry \`raw\`
 *  (\`{ source, payload }\`), the untranslated provider block the part was
 *  normalized from, for echoing a turn back to the model verbatim. */
type MessagePart =
  | { type: 'text'; text: string; raw?: RawOrigin }
  | { type: 'reasoning'; text: string; label?: string; index?: number; signature?: string; raw?: RawOrigin }
  | { type: 'tool'; tool: ToolPart; raw?: RawOrigin }
  | { type: 'card'; envelope: CardEnvelope; raw?: RawOrigin }
  | { type: 'source'; source: MessageSource; raw?: RawOrigin }
  | { type: 'file'; attachment: AttachmentData; raw?: RawOrigin };

interface ToolPart {
  type: string;
  /** Rendering classification. Derived from \`type\` when you omit it; an explicit
   *  value you set is preserved across later patches. */
  kind?: 'command' | 'file-change' | 'search' | 'fetch' | 'mcp' | 'image' | 'generic';
  state: 'input-streaming' | 'input-available' | 'output-available' | 'output-error';
  input?: Record<string, unknown>;
  /** Raw accumulated argument fragments, for character-level streaming. */
  rawInput?: string;
  output?: Record<string, unknown>;
  toolCallId?: string;
  errorText?: string;
  raw?: RawOrigin;
}

/** A citation. Exported as \`MessageSource\` (the bare \`Source\` name belongs to
 *  the citation-chip component). */
interface MessageSource { id?: string; url?: string; title?: string; snippet?: string; index?: number }
\`\`\`

The simplest possible message, and one with reasoning + a tool call before its answer:

\`\`\`js
{ id: '1', role: 'assistant', parts: [{ type: 'text', text: 'Hi!' }] }

{
  id: '2',
  role: 'assistant',
  parts: [
    { type: 'reasoning', text: 'I should search for current pricing.' },
    { type: 'tool', tool: { type: 'search', state: 'output-available', toolCallId: 'tc_1',
        input: { query: 'current pricing' }, output: { results: ['A', 'B'] } } },
    { type: 'text', text: 'Here is what I found.' },
  ],
}
\`\`\`

Types are importable: \`import type { ChatMessage, MessagePart, MessageSource } from '@kitn.ai/ui'\` (also from \`'@kitn.ai/ui/react'\` and \`'@kitn.ai/ui/state'\`).

## Framework wiring

**Plain HTML / CDN**
\`\`\`html
<script type="module" src="https://unpkg.com/@kitn.ai/ui/web-components"></script>
<kai-chat style="display:block;height:100vh"></kai-chat>
<script type="module">
  const chat = document.querySelector('kai-chat');
  chat.messages = [];
</script>
\`\`\`

**React** — typed wrappers auto-set properties and expose \`on<Event>\` props:
\`\`\`tsx
import { Chat } from '@kitn.ai/ui/react';
<Chat messages={messages} onSubmit={(e) => send(e.detail.value)} />
\`\`\`

**Vue** — use the element directly; pass arrays via \`.prop\`:
\`\`\`vue
<kai-chat :messages.prop="messages" @kai-submit="send" />
\`\`\`

## Theming

\`\`\`css
:root {
  --kai-color-background: #0f0f0f;
  --kai-color-primary: #7c3aed;
  --kai-color-muted: #1e1e1e;
}
\`\`\`

For plain HTML/CDN: \`<link rel="stylesheet" href="…/@kitn.ai/ui/theme.tokens.css">\`.
For Tailwind builds: \`@import "@kitn.ai/ui/theme.css"\` in your CSS.

## Docs

${fullOnlyPointers.join('\n')}
- Machine-readable Custom Elements Manifest: https://unpkg.com/@kitn.ai/ui/dist/custom-elements.json
- Working examples: https://github.com/kitn-ai/ui/tree/main/examples
- Storybook: https://storybook.kitn.dev
- Repository: https://github.com/kitn-ai/ui`;
}

// ---------------------------------------------------------------------------
// Per-web-component reference (the generated body of llms-full.txt).
// ---------------------------------------------------------------------------
function renderElement(el) {
  const react = el.reactName;
  const propRows = el.props
    .map((p) => {
      const attr = p.scalar ? `\`${toAttr(p.name)}\`` : '—';
      return `| \`${p.name}\` | ${attr} | \`${escapeCell(p.type)}\` | ${escapeCell(p.description)} |`;
    })
    .join('\n');

  const eventRows = el.events
    .map((e) => `| \`${e.name}\` | \`${escapeCell(e.detail || 'CustomEvent')}\` | ${escapeCell(e.description)} |`)
    .join('\n');

  const out = [`### \`${el.tag}\` / \`${react}\``, ''];

  out.push(
    propRows
      ? [
          '**Properties** (every element also accepts `theme="light|dark|auto"`; only scalar props work as HTML attributes):',
          '',
          '| Property | Attribute | Type | Description |',
          '|---|---|---|---|',
          propRows,
        ].join('\n')
      : '_No public properties._',
  );
  out.push('');
  out.push(
    eventRows
      ? [
          '**Events** (non-bubbling `CustomEvent`s — listen directly on the element):',
          '',
          '| Event | `detail` type | Description |',
          '|---|---|---|',
          eventRows,
        ].join('\n')
      : '_No events._',
  );

  // The imperative half of the interaction surface. An agent reading this file to
  // wire an element could previously see every prop and every event and no way to
  // drive the thing from code.
  if (el.methods?.length) {
    const [first] = el.methods;
    out.push('');
    out.push(
      [
        `**Methods** (call on the element instance: \`document.querySelector('${el.tag}').${first.name}(${first.params ? '…' : ''})\`):`,
        '',
        '| Method | Signature | Description |',
        '|---|---|---|',
        el.methods
          .map((m) => `| \`${m.name}\` | \`${escapeCell(`(${m.params}): ${m.returns}`)}\` | ${escapeCell(m.description)} |`)
          .join('\n'),
      ].join('\n'),
    );
  }

  if (el.slots?.length) {
    out.push('');
    out.push(
      [
        '**Slots** (project your own markup via `slot="name"` on a light-DOM child):',
        '',
        '| Slot | Mode | Description |',
        '|---|---|---|',
        el.slots
          .map((s) => `| ${s.name ? `\`${s.name}\`` : '_(default)_'} | ${s.mode ?? '—'} | ${escapeCell(s.doc)} |`)
          .join('\n'),
      ].join('\n'),
    );
  }

  // "Route 2": the light-DOM child elements this web component parses. The only way to
  // drive some web components from plain HTML with no JS, and previously in no generated
  // artifact at all — so an agent reading this file could not know they exist.
  if (el.declarativeChildren?.length) {
    out.push('');
    out.push(
      [
        '**Declarative children** (compose these in light DOM instead of setting the JS property):',
        '',
        '| Child element | Attributes | Text content | Notes |',
        '|---|---|---|---|',
        el.declarativeChildren
          .map((c) => `| \`<${c.tag}>\` | ${c.attributes.length ? c.attributes.map((a) => `\`${a}\``).join(', ') : '—'} | ${c.text ? 'yes' : '—'} | ${escapeCell(c.description ?? '')} |`)
          .join('\n'),
      ].join('\n'),
    );
  }

  if (el.parts?.length) {
    out.push('');
    out.push(
      [
        '**Styleable parts** (restyle from outside via `' + el.tag + '::part(name)`):',
        '',
        '| Part | Description |',
        '|---|---|',
        el.parts
          .map((p) => `| \`::part(${p.name})\` | ${escapeCell(p.doc)}${p.recipe ? ` — \`${escapeCell(p.recipe)}\`` : ''} |`)
          .join('\n'),
      ].join('\n'),
    );
  }

  if (el.vars?.length) {
    out.push('');
    out.push(
      [
        '**CSS custom properties** (set them on the element to change how it looks):',
        '',
        '| Property | Default | Description |',
        '|---|---|---|',
        el.vars
          .map((v) => `| \`${v.name}\` | ${v.default ? `\`${v.default}\`` : '—'} | ${escapeCell(v.doc)}${v.recipe ? ` — \`${escapeCell(v.recipe)}\`` : ''} |`)
          .join('\n'),
      ].join('\n'),
    );
  }

  out.push('');
  out.push('---');
  return out.join('\n');
}

const RUNBOOK = `## How to build a chat app in 5 steps

### 1 — Install
\`\`\`bash
npm install @kitn.ai/ui
\`\`\`

### 2 — Pick your layer
Drop-in: use \`<kai-chat>\` for a full chat UI in one tag (\`import '@kitn.ai/ui/web-components'\`).
Composable: combine \`<kai-message>\`, \`<kai-prompt-input>\`, \`<kai-reasoning>\`, … in your own markup.

### 3 — Handle \`submit\` and stream
\`\`\`js
import '@kitn.ai/ui/web-components';
// The streaming fold. It is 5 lines if you would rather inline it: see the
// Streaming recipe below.
import { appendTextPart } from '@kitn.ai/ui/state';

const chat = document.querySelector('kai-chat');
chat.messages = [];

chat.addEventListener('kai-submit', async (e) => {
  const userText = e.detail.value;

  // Append the user message (new array, see the streaming note)
  const history = [...chat.messages, { id: crypto.randomUUID(), role: 'user', parts: [{ type: 'text', text: userText }] }];
  chat.messages = history;
  chat.loading = true;

  // Add an empty assistant placeholder to stream into
  const aid = crypto.randomUUID();
  chat.messages = [...history, { id: aid, role: 'assistant', parts: [] }];

  for await (const token of streamFromYourAPI(history)) {
    // Fold each delta onto the message's TRAILING text part. Do NOT replace
    // \`parts\` wholesale: that drops reasoning/tool/card parts already on it.
    chat.messages = chat.messages.map((m) =>
      m.id === aid ? { ...m, parts: appendTextPart(m.parts, token) } : m);
  }
  chat.loading = false;
});
\`\`\`

### 4 — Wire optional features
- Reasoning: push \`{ type: 'reasoning', text: '…' }\` onto the message's \`parts\`.
- Tool calls: push \`{ type: 'tool', tool: { type: 'search', state: 'output-available', input: {…}, output: {…} } }\`.
- Model switcher: \`chat.models = [{ id: 'gpt-4o', name: 'GPT-4o' }]; chat.currentModel = 'gpt-4o';\` — listen for \`modelchange\`.
- Token meter: \`chat.context = { usedTokens: 1200, maxTokens: 128000 };\`.
- History sidebar: add \`<kai-conversations>\`; listen for \`select\` and \`newchat\`.

### 5 — Theme
Override \`--kai-color-*\` tokens on \`:root\` (they pierce Shadow DOM).`;

const STREAMING_RECIPE = `## Streaming recipe (critical)

Two rules, and both bite:

1. **Reassign a NEW array containing a NEW message object on every chunk.** Mutating an existing message object in place will NOT trigger a re-render.
2. **Fold the delta onto the message's TRAILING text part.** Replacing \`parts\` with a fresh single-text array re-renders fine but silently deletes any reasoning / tool / card parts the turn already produced.

\`\`\`js
// The fold. \`@kitn.ai/ui/state\` exports exactly this as \`appendTextPart\`.
const appendText = (parts, delta) => {
  const last = parts[parts.length - 1];
  return last?.type === 'text'
    ? [...parts.slice(0, -1), { ...last, text: last.text + delta }]
    : [...parts, { type: 'text', text: delta }];
};

// ✅ re-renders, and keeps every part already on the message
chat.messages = chat.messages.map((m) =>
  m.id === id ? { ...m, parts: appendText(m.parts, delta) } : m);

// ❌ does NOT re-render (same array, same object)
chat.messages[i].parts = appendText(chat.messages[i].parts, delta);

// ❌ re-renders, but drops the message's reasoning/tool/card parts
chat.messages = chat.messages.map((m) =>
  m.id === id ? { ...m, parts: [{ type: 'text', text: answer }] } : m);
\`\`\`

Opening a new text part when the last part is not text is what stops a post-tool answer being glued onto the pre-tool text.

The same reassign rule applies to every array/object property (\`models\`, \`context\`, \`suggestions\`, …): replace, don't mutate.`;

// ---------------------------------------------------------------------------
// The sections that exist ONLY in llms-full.txt. ONE structure drives both
// artifacts: `generate()` composes llms-full.txt's body from `render`, and
// llms.txt's Docs bullets from `pointer` — so a section cannot be added to the
// full file without the compact index gaining a pointer to it. That is the
// invariant that makes the llms.txt/llms-full.txt split work at all: the small
// file is only useful while it lets an agent NAVIGATE into the big one instead
// of ingesting ~300 KB wholesale, and the runbook + streaming recipe had
// already rotted into unindexed sections before this structure existed.
//
// `key` must appear verbatim both in the section's own `## ` heading and in its
// pointer line; `generate()` throws on either drift, and
// tests/scripts/llms-index-coverage.test.ts asserts the committed artifacts
// agree (including that NO top-level heading of llms-full.txt is unregistered).
// ---------------------------------------------------------------------------
export const FULL_ONLY_SECTIONS = [
  {
    key: 'Element reference',
    pointer: (count) =>
      `- Element reference (all ${count} elements, every prop/event/method/slot/part): the "Element reference" section of ./llms-full.txt — https://kitn.dev/llms-full.txt`,
    render: ({ count, webComponentSection }) =>
      [
        `## Element reference (${count} elements, generated from custom-elements.json)`,
        '',
        'Every element also accepts the `theme` attribute. Array/object properties are marked with a `—` attribute: they must be set as JS properties.',
        '',
        webComponentSection,
      ].join('\n'),
  },
  {
    key: 'Programmatic layer',
    pointer: () =>
      '- Programmatic layer (`@kitn.ai/ui/state` + `@kitn.ai/ui/wire`: streaming folds, the mock responder, the SSE readers/encoders): the "Programmatic layer" section of llms-full.txt',
    render: ({ programmaticMarkdown }) => programmaticMarkdown,
  },
  {
    key: 'How to build a chat app in 5 steps',
    pointer: () =>
      '- How to build a chat app in 5 steps (install → pick a layer → handle submit + stream → wire features → theme, with working code): the "How to build a chat app in 5 steps" section of llms-full.txt',
    render: () => RUNBOOK,
  },
  {
    key: 'Streaming recipe',
    pointer: () =>
      '- Streaming recipe (the two rules that bite: reassign new references per chunk, fold deltas onto the trailing text part): the "Streaming recipe" section of llms-full.txt',
    render: () => STREAMING_RECIPE,
  },
  {
    key: 'Icon roster',
    pointer: () =>
      '- Icon roster (every name `kai-icon` and the elements\' `icon` props resolve; anything else fails loud): the "Icon roster" section of llms-full.txt',
    render: ({ icons }) =>
      [
        `## Icon roster (${icons.length} names, derived from NAMED_ICONS in src/components/icon/icon.tsx)`,
        '',
        'Every name `kai-icon` (and every `icon` prop/attribute across the elements) resolves — ' +
          'derived from the `NAMED_ICONS` map in `src/components/icon/icon.tsx` (also exported at runtime as ' +
          '`ICON_NAMES`). An icon-shaped name outside this roster renders a fallback glyph and ' +
          'logs a console error, in dev and prod alike; URLs render an `<img>`, and ' +
          'emoji/arbitrary text passes through as text.',
        '',
        icons.map((n) => `\`${n}\``).join(' · '),
      ].join('\n'),
  },
];

// The order sections appear in llms-full.txt: prose first, the big generated
// reference last. Separate from the pointer order above, which leads with the
// reference because it is what most readers of llms.txt come for.
const FULL_BODY_ORDER = [
  'How to build a chat app in 5 steps',
  'Streaming recipe',
  'Programmatic layer',
  'Icon roster',
  'Element reference',
];

/**
 * Top-level `## ` headings of a markdown document, skipping fenced code blocks
 * (snippets legitimately contain `## `-looking lines). Exported for the
 * coverage test, which derives "what must llms.txt index" from it.
 */
export function topLevelHeadings(markdown) {
  const out = [];
  let inFence = false;
  for (const line of markdown.split('\n')) {
    if (/^\s*```/.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (!inFence && line.startsWith('## ')) out.push(line.trimEnd());
  }
  return out;
}

// ---------------------------------------------------------------------------
// Normalize the data model: accept either the in-memory `elements` array from
// gen-web-component-api.mjs OR the dist/custom-elements.json declarations.
// ---------------------------------------------------------------------------
function fromElements(elements) {
  return elements.map((el) => ({
    tag: el.tag,
    reactName: el.displayName ?? tagToReact(el.tag).replace(/^Kai/, ''),
    props: el.props.map((p) => ({
      name: p.name,
      type: p.type,
      scalar: p.scalar,
      description: p.description,
    })),
    events: el.events.map((e) => ({
      name: e.name,
      detail: e.detail ? `CustomEvent<${e.detail}>` : 'CustomEvent',
      description: e.description,
    })),
    methods: (el.methods ?? []).map((m) => ({
      name: m.name,
      params: m.params,
      returns: m.returns,
      description: m.description,
    })),
    slots: el.slots,
    parts: el.parts,
    vars: el.vars,
    declarativeChildren: el.declarativeChildren,
  }));
}

function fromManifest(cem) {
  const decls = cem.modules[0].declarations;
  return decls.map((d) => {
    const attrByField = new Map(
      (d.attributes || []).filter((a) => a.fieldName).map((a) => [a.fieldName, a]),
    );
    return {
      tag: d.tagName,
      reactName: tagToReact(d.tagName).replace(/^Kai/, ''),
      props: (d.members || [])
        .filter((m) => m.kind === 'field')
        .map((m) => ({
          name: m.name,
          type: m.type?.text ?? 'unknown',
          scalar: attrByField.has(m.name) || isScalarType(m.type?.text ?? ''),
          description: m.description ?? '',
        })),
      events: (d.events || []).map((e) => ({
        name: e.name,
        detail: e.type?.text ?? 'CustomEvent',
        description: e.description ?? '',
      })),
      // Must stay in step with `fromElements` above. This path is the standalone
      // fallback, and a field it forgets does not fail — it silently writes a
      // THINNER llms-full.txt over the full one (see the header note and CLAUDE.md).
      // The CEM packs the whole authored parameter list into `parameters[0].name`.
      methods: (d.members || [])
        .filter((m) => m.kind === 'method')
        .map((m) => ({
          name: m.name,
          params: m.parameters?.[0]?.name ?? '',
          returns: m.return?.type?.text ?? 'void',
          description: m.description ?? '',
        })),
      slots: (d.slots || []).map((s) => ({ name: s.name, doc: s.description ?? '' })),
      parts: (d.cssParts || []).map((p) => ({ name: p.name, doc: p.description ?? '', recipe: p.recipe })),
      // Consumer-settable custom properties. Tokens land in the same CEM array as
      // `{ name }` with no description (they are palette entries, not knobs), so a
      // DESCRIPTION is what marks a var. Keep this filter in step with
      // gen-web-component-api's emission or this path silently drops the vars — the
      // failure mode the note above describes, on the field added for them.
      vars: (d.cssProperties || [])
        .filter((p) => p.description)
        .map((p) => ({ name: p.name, doc: p.description, default: p.default, recipe: p.recipe })),
      declarativeChildren: (d.declarativeChildren || []).map((c) => ({
        tag: c.tagName,
        attributes: (c.attributes || []).map((a) => a.name),
        text: !!c.textContent,
        description: c.description ?? '',
      })),
    };
  });
}

export function generate(webComponentsInput) {
  const els = webComponentsInput ? fromElements(webComponentsInput) : fromManifest(
    JSON.parse(readFileSync(resolve(root, 'dist/custom-elements.json'), 'utf8')),
  );
  els.sort((a, b) => a.tag.localeCompare(b.tag));
  const count = els.length;

  const webComponentSection = els.map(renderElement).join('\n\n');
  // Derived from dist/state/*.d.ts + dist/wire/*.d.ts — the layer a builder
  // that leaves <kai-chat> writes against, previously on no surface (F-46).
  const programmatic = buildProgrammaticSection();
  const ctx = {
    count,
    webComponentSection,
    programmaticMarkdown: programmatic.markdown,
    icons: iconNames(root),
  };

  // Every full-only section, rendered, with its key/heading/pointer coupling
  // enforced LOUDLY at generation time. A section whose heading no longer
  // carries its key (or whose pointer no longer names it) would let llms.txt
  // stop indexing it while every substring check stayed green.
  const orderedSections = FULL_BODY_ORDER.map((key) => {
    const section = FULL_ONLY_SECTIONS.find((s) => s.key === key);
    if (!section) throw new Error(`gen-llms: FULL_BODY_ORDER names an unregistered section "${key}"`);
    return section;
  });
  if (orderedSections.length !== FULL_ONLY_SECTIONS.length) {
    throw new Error('gen-llms: FULL_BODY_ORDER must place every FULL_ONLY_SECTIONS entry');
  }
  const renderedSections = orderedSections.map((section) => {
    const markdown = section.render(ctx);
    // First TOP-LEVEL heading, not first line: the programmatic section opens
    // with its `<!-- kai:programmatic:start -->` slice marker, which is fine.
    const heading = topLevelHeadings(markdown)[0] ?? '';
    if (!heading.includes(section.key)) {
      throw new Error(
        `gen-llms: section "${section.key}"'s first \`## \` heading does not contain its key ` +
          `(got: ${JSON.stringify(heading)}). The key is what llms.txt's derived pointer names.`,
      );
    }
    if (!section.pointer(count).includes(section.key)) {
      throw new Error(`gen-llms: the pointer for "${section.key}" does not mention the key it points at`);
    }
    return markdown;
  });

  const llmsBody = buildLlmsBody(count, FULL_ONLY_SECTIONS.map((s) => s.pointer(count)));
  const llmsTxt = `${HEADER_NOTE}\n${llmsBody}\n`;

  const llmsFull = [
    HEADER_NOTE,
    '# @kitn.ai/ui — Full Reference',
    '',
    llmsBody,
    '',
    ...renderedSections.flatMap((markdown) => ['---', '', markdown, '']),
  ].join('\n') + '\n';

  writeFileSync(resolve(root, 'llms.txt'), llmsTxt);
  writeFileSync(resolve(root, 'llms-full.txt'), llmsFull);
  // NO dist/llms/ copies (owner-ruled 2026-08-25) and NO standalone
  // programmatic.md: the package-root files above are the canonical, only
  // shipped copies, and the MCP's { name: "programmatic" } topic slices the
  // marker-fenced section back out of the root llms-full.txt. Each duplicate
  // was real tarball weight (verify:pack priced them — ~50 KB for
  // programmatic.md, ~293 KB for the dist llms-full copy). Remove stale
  // copies from earlier builds so they cannot keep shipping — dist/ is
  // packed wholesale.
  rmSync(resolve(root, 'dist/llms'), { recursive: true, force: true });

  console.log(
    `✓ llms.txt + llms-full.txt written (${count} elements, ${programmatic.exportCount} state/wire exports)`,
  );
  return count;
}

// Run standalone: read the manifest from disk.
// pathToFileURL, NOT `file://${process.argv[1]}`: import.meta.url percent-encodes and
// a path does not, so on a checkout under `/My Repo/` the hand-built string never
// matched and this exited 0 without writing llms.txt or llms-full.txt.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  generate();
}
