/// <reference types="svelte" />
/// <reference types="vite/client" />

// No `declare namespace svelteHTML` block here any more, and that is load-bearing
// rather than tidiness. It aliased each kai-* tag to `Record<string, unknown>`,
// which accepts any attribute of any type — and a permissive declaration of the
// same tag WINS over the kit's typed one instead of colliding with it. MEASURED
// with this starter's own `svelte-check`: with those six lines back in place, a
// deliberately wrong `variant="solid"` on <kai-button> in ThemeToggle.svelte
// reports 0 errors; with them dropped, the same file reports
// `Type '"solid"' is not assignable to type '"default" | "subtle" | "ghost" |
// "outline" | "destructive" | undefined'`. No TS2717 either way.
//
// @kitn.ai/ui/web-components ships a real `svelteHTML.IntrinsicElements`
// augmentation (generated by packages/ui/scripts/gen-web-component-types.mjs from
// the same registry as the vue and react ones), so the tags this example uses —
// and their attributes — are typed by the kit: `theme`, `variant="ghost"`,
// `size="icon"`, `size="280px"`, and the `onkai-*` handlers below are checked
// against the elements' own props and events. A tag this example adds that the kit
// does not register is unchecked again until it is registered, which is the one
// thing this file would have to re-open a permissive block for.
