// Generates `llms.txt` (curated orientation, llmstxt.org convention) and
// `llms-full.txt` (full per-element API reference) for AI coding agents.
//
// Source of truth = the same `elements` model that `gen-element-api.mjs` uses
// to write dist/custom-elements.json, so these files can never drift from the
// shipped API. When run standalone (no in-memory import) it falls back to
// reading dist/custom-elements.json.
//
// Outputs (all deterministic — no timestamps/random):
//   - llms.txt              (repo root, committed + npm `files`)
//   - llms-full.txt         (repo root, committed + npm `files`)
//   - dist/llms/llms.txt    (copy, shipped in the npm package)
//   - dist/llms/llms-full.txt

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const toAttr = (name) => name.replace(/([A-Z])/g, '-$1').toLowerCase();
const tagToReact = (tag) =>
  tag.split('-').map((s) => s[0].toUpperCase() + s.slice(1)).join('');
const escapeCell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ').trim();
const isScalarType = (t) =>
  /^(undefined\s*\|\s*)?('[^']*'(\s*\|\s*'[^']*')*|string|number|boolean|true|false)(\s*\|\s*undefined)?$/.test(
    t.replace(/\s+/g, ' ').trim(),
  );

const HEADER_NOTE = '<!-- AUTO-GENERATED by scripts/gen-llms.mjs — do not edit by hand. Run `npm run build`. -->';

// ---------------------------------------------------------------------------
// Curated orientation content (the body of llms.txt). Kept inline so the
// generator owns the canonical copy.
// ---------------------------------------------------------------------------
function buildLlmsBody(count) {
  return `# @kitn.ai/ui

> Framework-agnostic, Shadow-DOM web components for building AI chat interfaces — works in React, Vue, Angular, Svelte, or plain HTML. ${count} custom elements, every one prefixed \`kai-\` (e.g. \`<kai-chat>\`, \`<kai-artifact>\`): streaming responses, markdown + code rendering, reasoning/tool panels, attachments, conversation sidebar, voice input. Zero framework dependency for consumers; the SolidJS runtime it is authored in is bundled in, so the host needs nothing.

## Install

\`\`\`bash
npm install @kitn.ai/ui
# SolidJS consumers also need the peer dep:
npm install solid-js
\`\`\`

## #1 rule: array/object data goes on JS PROPERTIES, not HTML attributes

This is the single most common mistake. Arrays and objects (\`messages\`, \`models\`, \`context\`, \`suggestions\`, \`slashCommands\`, …) MUST be assigned as JavaScript properties on the element. They CANNOT be passed as HTML attributes — an HTML attribute is always a string and will be ignored or mis-parsed.

\`\`\`js
const chat = document.querySelector('kai-chat');
chat.messages = [{ id: '1', role: 'assistant', content: 'Hi!' }]; // ✅ property
\`\`\`
\`\`\`html
<kai-chat messages="[...]"></kai-chat>  <!-- ❌ never works -->
\`\`\`

Only scalar values (string/number/boolean) work as attributes (e.g. \`placeholder\`, \`loading\`, \`theme\`).

## Two layers

**Layer 1 — batteries-included web components** (\`import '@kitn.ai/ui/elements'\`):
Drop an element into any framework (React, Vue, plain HTML). Data in via JS properties; interactions out via non-bubbling CustomEvents.

- \`<kai-chat>\` — full chat UI (message list + prompt input). The primary starting point.
- \`<kai-conversations>\` — sidebar conversation browser with group support.
- \`<kai-prompt-input>\` — standalone composer with send button.

**Layer 2 — composable primitives** (\`import { … } from '@kitn.ai/ui'\`):
All ${count} elements are also exported individually. Use them for custom layouts or features \`<kai-chat>\` does not expose (ChainOfThought, FeedbackBar, ThinkingBar, VoiceInput, …). Your bundler tree-shakes the rest.

## Key rules for the web components

1. **Array/object data = JS properties** (see above). Scalars may be attributes.
2. **Events are non-bubbling \`CustomEvent\`s** — listen directly on the element:
   \`chat.addEventListener('kai-submit', (e) => console.log(e.detail.value))\`
3. **\`theme\` attribute** (\`'light' | 'dark' | 'auto'\`) works on every element. Default \`auto\` follows \`prefers-color-scheme\`.
4. **Theming via CSS custom properties** — override \`--kai-color-*\` tokens on \`:root\`; they pierce Shadow DOM.

## ChatMessage schema (required for \`<kai-chat>\`)

\`\`\`ts
interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  reasoning?: { text: string; label?: string };
  tools?: ToolPart[];
  attachments?: AttachmentData[];
  actions?: ('copy' | 'like' | 'dislike' | 'regenerate' | 'edit')[];
}
\`\`\`

## Framework wiring

**Plain HTML / CDN**
\`\`\`html
<script type="module" src="https://unpkg.com/@kitn.ai/ui/elements"></script>
<kai-chat style="display:block;height:100vh"></kai-chat>
<script type="module">
  const chat = document.querySelector('kai-chat');
  chat.messages = [];
</script>
\`\`\`

**React** — typed wrappers auto-set properties and expose \`on<Event>\` props:
\`\`\`tsx
import { Chat } from '@kitn.ai/ui/react';
<Chat messages={messages} onSubmit={(e) => send(e.detail.value)} />
\`\`\`

**Vue** — use the element directly; pass arrays via \`.prop\`:
\`\`\`vue
<kai-chat :messages.prop="messages" @kai-submit="send" />
\`\`\`

## Theming

\`\`\`css
:root {
  --kai-color-background: #0f0f0f;
  --kai-color-primary: #7c3aed;
  --kai-color-muted: #1e1e1e;
}
\`\`\`

For plain HTML/CDN: \`<link rel="stylesheet" href="…/@kitn.ai/ui/theme.tokens.css">\`.
For Tailwind builds: \`@import "@kitn.ai/ui/theme.css"\` in your CSS.

## Docs

- Full element reference (all ${count} elements, every prop/event): ./llms-full.txt — https://kitn.dev/llms-full.txt
- Machine-readable Custom Elements Manifest: https://unpkg.com/@kitn.ai/ui/dist/custom-elements.json
- Working examples: https://github.com/kitn-ai/ui/tree/main/examples
- Storybook: https://storybook.kitn.dev
- Repository: https://github.com/kitn-ai/ui`;
}

// ---------------------------------------------------------------------------
// Per-element reference (the generated body of llms-full.txt).
// ---------------------------------------------------------------------------
function renderElement(el) {
  const react = el.reactName;
  const propRows = el.props
    .map((p) => {
      const attr = p.scalar ? `\`${toAttr(p.name)}\`` : '—';
      return `| \`${p.name}\` | ${attr} | \`${escapeCell(p.type)}\` | ${escapeCell(p.description)} |`;
    })
    .join('\n');

  const eventRows = el.events
    .map((e) => `| \`${e.name}\` | \`${escapeCell(e.detail || 'CustomEvent')}\` | ${escapeCell(e.description)} |`)
    .join('\n');

  const out = [`### \`${el.tag}\` / \`${react}\``, ''];

  out.push(
    propRows
      ? [
          '**Properties** (every element also accepts `theme="light|dark|auto"`; only scalar props work as HTML attributes):',
          '',
          '| Property | Attribute | Type | Description |',
          '|---|---|---|---|',
          propRows,
        ].join('\n')
      : '_No public properties._',
  );
  out.push('');
  out.push(
    eventRows
      ? [
          '**Events** (non-bubbling `CustomEvent`s — listen directly on the element):',
          '',
          '| Event | `detail` type | Description |',
          '|---|---|---|',
          eventRows,
        ].join('\n')
      : '_No events._',
  );
  out.push('');
  out.push('---');
  return out.join('\n');
}

const RUNBOOK = `## How to build a chat app in 5 steps

### 1 — Install
\`\`\`bash
npm install @kitn.ai/ui
\`\`\`

### 2 — Pick your layer
Drop-in: use \`<kai-chat>\` for a full chat UI in one tag (\`import '@kitn.ai/ui/elements'\`).
Composable: combine \`<kai-message>\`, \`<kai-prompt-input>\`, \`<kai-reasoning>\`, … in your own markup.

### 3 — Handle \`submit\` and stream
\`\`\`js
import '@kitn.ai/ui/elements';
const chat = document.querySelector('kai-chat');
chat.messages = [];

chat.addEventListener('kai-submit', async (e) => {
  const userText = e.detail.value;

  // Append the user message (new array — see streaming note)
  const history = [...chat.messages, { id: crypto.randomUUID(), role: 'user', content: userText }];
  chat.messages = history;
  chat.loading = true;

  // Add an empty assistant placeholder to stream into
  const aid = crypto.randomUUID();
  chat.messages = [...history, { id: aid, role: 'assistant', content: '' }];

  let answer = '';
  for await (const token of streamFromYourAPI(history)) {
    answer += token;
    chat.messages = chat.messages.map((m) => (m.id === aid ? { ...m, content: answer } : m));
  }
  chat.loading = false;
});
\`\`\`

### 4 — Wire optional features
- Reasoning: add \`reasoning: { text: '…' }\` to an assistant message.
- Tool calls: add \`tools: [{ type: 'search', state: 'output-available', input: {…}, output: {…} }]\`.
- Model switcher: \`chat.models = [{ id: 'gpt-4o', name: 'GPT-4o' }]; chat.currentModel = 'gpt-4o';\` — listen for \`modelchange\`.
- Token meter: \`chat.context = { usedTokens: 1200, maxTokens: 128000 };\`.
- History sidebar: add \`<kai-conversations>\`; listen for \`select\` and \`newchat\`.

### 5 — Theme
Override \`--kai-color-*\` tokens on \`:root\` (they pierce Shadow DOM).`;

const STREAMING_RECIPE = `## Streaming recipe (critical)

To update messages while streaming, **reassign a NEW array containing a NEW message object** on every chunk. Mutating an existing message object in place will NOT trigger a re-render:

\`\`\`js
// ✅ re-renders
chat.messages = chat.messages.map((m) => (m.id === id ? { ...m, content: next } : m));

// ❌ does NOT re-render
chat.messages[i].content = next;
\`\`\`

The same rule applies to every array/object property (\`models\`, \`context\`, \`suggestions\`, …): replace, don't mutate.`;

// ---------------------------------------------------------------------------
// Normalize the data model: accept either the in-memory `elements` array from
// gen-element-api.mjs OR the dist/custom-elements.json declarations.
// ---------------------------------------------------------------------------
function fromElements(elements) {
  return elements.map((el) => ({
    tag: el.tag,
    reactName: el.displayName ?? tagToReact(el.tag).replace(/^Kai/, ''),
    props: el.props.map((p) => ({
      name: p.name,
      type: p.type,
      scalar: p.scalar,
      description: p.description,
    })),
    events: el.events.map((e) => ({
      name: e.name,
      detail: e.detail ? `CustomEvent<${e.detail}>` : 'CustomEvent',
      description: e.description,
    })),
  }));
}

function fromManifest(cem) {
  const decls = cem.modules[0].declarations;
  return decls.map((d) => {
    const attrByField = new Map(
      (d.attributes || []).filter((a) => a.fieldName).map((a) => [a.fieldName, a]),
    );
    return {
      tag: d.tagName,
      reactName: tagToReact(d.tagName).replace(/^Kai/, ''),
      props: (d.members || [])
        .filter((m) => m.kind === 'field')
        .map((m) => ({
          name: m.name,
          type: m.type?.text ?? 'unknown',
          scalar: attrByField.has(m.name) || isScalarType(m.type?.text ?? ''),
          description: m.description ?? '',
        })),
      events: (d.events || []).map((e) => ({
        name: e.name,
        detail: e.type?.text ?? 'CustomEvent',
        description: e.description ?? '',
      })),
    };
  });
}

export function generate(elementsInput) {
  const els = elementsInput ? fromElements(elementsInput) : fromManifest(
    JSON.parse(readFileSync(resolve(root, 'dist/custom-elements.json'), 'utf8')),
  );
  els.sort((a, b) => a.tag.localeCompare(b.tag));
  const count = els.length;

  const llmsBody = buildLlmsBody(count);
  const llmsTxt = `${HEADER_NOTE}\n${llmsBody}\n`;

  const elementSection = els.map(renderElement).join('\n\n');
  const llmsFull = [
    HEADER_NOTE,
    '# @kitn.ai/ui — Full Reference',
    '',
    llmsBody,
    '',
    '---',
    '',
    RUNBOOK,
    '',
    '---',
    '',
    STREAMING_RECIPE,
    '',
    '---',
    '',
    `## Element reference (${count} elements, generated from custom-elements.json)`,
    '',
    'Every element also accepts the `theme` attribute. Array/object properties are marked with a `—` attribute: they must be set as JS properties.',
    '',
    elementSection,
    '',
  ].join('\n') + '\n';

  mkdirSync(resolve(root, 'dist/llms'), { recursive: true });
  writeFileSync(resolve(root, 'llms.txt'), llmsTxt);
  writeFileSync(resolve(root, 'llms-full.txt'), llmsFull);
  writeFileSync(resolve(root, 'dist/llms/llms.txt'), llmsTxt);
  writeFileSync(resolve(root, 'dist/llms/llms-full.txt'), llmsFull);

  console.log(`✓ llms.txt + llms-full.txt written (${count} elements)`);
  return count;
}

// Run standalone: read the manifest from disk.
if (import.meta.url === `file://${process.argv[1]}`) {
  generate();
}
