// Sync the docs site to the LIVE kit build — not a committed snapshot.
//
// Copies, from the repo root:
//   dist/*.js                       → public/kitn/      (the kc-* element bundle
//                                      + its hashed Shiki language/theme chunks,
//                                      loaded at runtime by example/kit.ts)
//   src/elements/element-meta.json  → src/data/         (props/events/composedFrom
//                                      tables — generated by `npm run build:api`)
//   src/elements/framework-usage.json → src/data/       (per-framework usage
//                                      snippets — generated by `gen-framework-usage`)
//
// Both targets are gitignored: the site always reflects the kit it was built
// against, and the hashed chunk names stay in lockstep with the bundle. Run on
// `predev`/`prebuild` (see package.json). If the kit hasn't been built yet, this
// builds it first so a fresh clone's `npm run dev` just works.
import { execSync } from 'node:child_process';
import {
  cpSync, existsSync, mkdirSync, readdirSync, rmSync, copyFileSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const docsRoot = resolve(here, '..');
const repoRoot = resolve(docsRoot, '..');

const dist = join(repoRoot, 'dist');
const metas = [
  join(repoRoot, 'src/elements/element-meta.json'),
  join(repoRoot, 'src/elements/framework-usage.json'),
];

const haveDist = existsSync(join(dist, 'kitn-chat.es.js'));
const haveMetas = metas.every(existsSync);

if (!haveDist || !haveMetas) {
  console.log('[sync-kit] kit build outputs missing — building the kit (npm run build)…');
  execSync('npm run build', { cwd: repoRoot, stdio: 'inherit' });
}

// 1. Bundle + chunks → public/kitn (clean copy so stale hashed chunks don't pile up)
const kitnOut = join(docsRoot, 'public/kitn');
rmSync(kitnOut, { recursive: true, force: true });
mkdirSync(kitnOut, { recursive: true });
const jsFiles = readdirSync(dist).filter((f) => f.endsWith('.js'));
for (const f of jsFiles) copyFileSync(join(dist, f), join(kitnOut, f));

// 2. Generator metas → src/data
const dataOut = join(docsRoot, 'src/data');
mkdirSync(dataOut, { recursive: true });
for (const m of metas) cpSync(m, join(dataOut, m.split('/').pop()));

console.log(`[sync-kit] synced ${jsFiles.length} bundle file(s) + ${metas.length} meta(s) from the live kit build.`);
