// Sync the docs site to the LIVE kit build — not a committed snapshot.
//
// Copies, from the repo root:
//   dist/*.js        → public/kitn/          (the register-all bundle kitn-chat.es.js
//                                             + any root chunks)
//   dist/elements/   → public/kitn/elements/ (per-element modules, the autoloader, and
//                                             the shared/lazy chunks — kitn-chat.es.js
//                                             imports ./elements/chunks/* at runtime, so
//                                             this subtree MUST be preserved, not flattened)
//   src/elements/element-meta.json  → src/data/         (props/events/composedFrom
//                                      tables — generated by `npm run build:api`)
//   src/elements/framework-usage.json → src/data/       (per-framework usage
//                                      snippets — generated by `gen-framework-usage`)
//
// Both targets are gitignored: the site always reflects the kit it was built
// against, and the hashed chunk names stay in lockstep with the bundle. Run on
// `predev`/`prebuild` (see package.json). If the kit hasn't been built yet, this
// builds it first so a fresh clone's `npm run dev` just works.
import { execSync } from 'node:child_process';
import {
  cpSync, existsSync, mkdirSync, readdirSync, rmSync, copyFileSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const docsRoot = resolve(here, '..');
const repoRoot = resolve(docsRoot, '..');

const dist = join(repoRoot, 'dist');
const metas = [
  join(repoRoot, 'src/elements/element-meta.json'),
  join(repoRoot, 'src/elements/framework-usage.json'),
];
// llms.txt / llms-full.txt → served at the site root (ui.kitn.ai/llms.txt) for
// AI agents. Generated by build:api alongside the metas.
const llms = [join(repoRoot, 'llms.txt'), join(repoRoot, 'llms-full.txt')];

const haveDist = existsSync(join(dist, 'kitn-chat.es.js'));
const haveMetas = metas.every(existsSync);
const haveLlms = llms.every(existsSync);

if (!haveDist || !haveMetas || !haveLlms) {
  console.log('[sync-kit] kit build outputs missing — building the kit (npm run build)…');
  execSync('npm run build', { cwd: repoRoot, stdio: 'inherit' });
}

// 1. Bundle + chunks → public/kitn (clean copy so stale hashed chunks don't pile up)
const kitnOut = join(docsRoot, 'public/kitn');
rmSync(kitnOut, { recursive: true, force: true });
mkdirSync(kitnOut, { recursive: true });
const jsFiles = readdirSync(dist).filter((f) => f.endsWith('.js'));
for (const f of jsFiles) copyFileSync(join(dist, f), join(kitnOut, f));
// The per-element + shared-chunk subtree. kitn-chat.es.js imports `./elements/chunks/*`
// (register-impl, the highlighter, lazy Shiki chunks, …) so this MUST keep its structure.
const elementsDir = join(dist, 'elements');
if (existsSync(elementsDir)) cpSync(elementsDir, join(kitnOut, 'elements'), { recursive: true });

// 2. Generator metas → src/data
const dataOut = join(docsRoot, 'src/data');
mkdirSync(dataOut, { recursive: true });
for (const m of metas) cpSync(m, join(dataOut, m.split('/').pop()));

// 3. llms.txt / llms-full.txt → public/ (served at ui.kitn.ai/llms.txt)
const publicOut = join(docsRoot, 'public');
for (const f of llms) copyFileSync(f, join(publicOut, f.split('/').pop()));

console.log(`[sync-kit] synced ${jsFiles.length} bundle file(s) + ${metas.length} meta(s) + ${llms.length} llms file(s) from the live kit build.`);
