// src/web-components/resizable.globals.d.ts
// Hand-authored ambient types for the cross-element maximize PROTOCOL — the two
// raw composed CustomEvents `<kai-artifact>` and `<kai-resizable>`/`<kai-resizable-item>`
// exchange. The generated web-component-types.d.ts emits no HTMLElementEventMap entries,
// so without this `el.addEventListener('kai-maximize-intent', e => e.detail)` is
// TS2339 on `Event`. NOT regenerated by `npm run build`.
//
// THE FILENAME IS LOAD-BEARING and must not go back to `resizable.d.ts`.
// TypeScript drops a .d.ts when a same-named .ts/.tsx sits beside it, and
// `resizable.tsx` does. Under the old name this whole file was in NO tsc
// program, so every augmentation below was inert. Measured on the same probe,
// `el.addEventListener('kai-maximize-intent', e => e.detail)`:
//   resizable.d.ts         TS2339: Property 'detail' does not exist on 'Event'
//   resizable.globals.d.ts clean -- narrowed to CustomEvent<KaiMaximizeIntentDetail>
//
// This file used to ALSO declare a global `KaiResizableElement` carrying
// `maximize`/`restore` plus an HTMLElementTagNameMap entry pointing at it. That
// half never worked: web-component-types.d.ts declares its own module-scoped
// `KaiResizableElement` and maps the tag to THAT, so the two entries collided
// (TS2717, invisible under the `skipLibCheck: true` every pass sets) and the
// generated one won — `document.querySelector('kai-resizable').maximize(0)` stayed
// TS2339. The methods now come from the GENERATOR (resizable.tsx routes them
// through `ctx.expose`, gen-web-component-types.mjs emits them onto the element
// interface), so the duplicate is gone and there is exactly one declaration of
// each name. Do not reintroduce it: a hand-written interface cannot win against
// the generated one, and generated files are regenerated.
import type { KaiMaximizeIntentDetail, KaiMaximizeStateDetail } from './resizable';

declare global {
  interface HTMLElementEventMap {
    'kai-maximize-intent': CustomEvent<KaiMaximizeIntentDetail>;
    'kai-maximize-state': CustomEvent<KaiMaximizeStateDetail>;
  }
}

export {};
