/** Live demo for the "Open an artifact from a message" pattern.
 *  The Claude/ChatGPT canvas reveal: the conversation starts full-width with NO
 *  artifact on screen. An assistant turn carries a custom `open-preview` action
 *  (and shows the generated file as an attachment); clicking it fires
 *  `kai-message-action`, and the host reveals a <kai-artifact> panel by un-hiding a
 *  <kai-resizable-item>. A close button collapses the panel back to full width.
 *
 *  The trigger is fully prop-driven — a real kai-chat custom action + its real
 *  event — not a CSS/shadow hack. The same-origin fixtures in public/artifact-demo/
 *  frame live in the preview iframe. */
import { createSignal, createEffect, onMount, onCleanup } from 'solid-js';
import { loadKit } from './example/kit';
import IconClose from '~icons/lucide/x';

// Same-origin fixtures served from public/artifact-demo/ — BASE_URL is '/' (root);
// strip any trailing slash so the URL is always '/artifact-demo/…'.
const base = import.meta.env.BASE_URL.replace(/\/$/, '');
const url = (p: string) => `${base}/artifact-demo/${p}`;

interface ProjectFile {
  path: string;
  url?: string;
  code?: string;
  language?: string;
  type?: 'html' | 'image' | 'pdf' | 'other';
}

const INDEX_HTML = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="styles.css" />
    <title>Starboard</title>
  </head>
  <body>
    <h1>Starboard</h1>
    <p>A landing page generated by the assistant, framed live in the artifact preview.</p>
    <div class="card">
      <strong>Ship faster</strong>
      <p>Open the artifact to read or edit the source, or open it in a new tab.</p>
    </div>
    <nav><a href="about.html">About →</a></nav>
  </body>
</html>`;

const ABOUT_HTML = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="styles.css" />
    <title>Starboard — About</title>
  </head>
  <body>
    <h1>About Starboard</h1>
    <p>Built with AI/UI artifacts — a sandboxed preview paired with the source.</p>
    <nav><a href="index.html">← Home</a></nav>
  </body>
</html>`;

const STYLES_CSS = `:root { --accent: #d6207f; --ink: #1b1b1f; }
body {
  font-family: system-ui, sans-serif;
  max-width: 40rem;
  margin: 0 auto;
  padding: 2.5rem 1.5rem;
  color: var(--ink);
  line-height: 1.6;
}
h1 { color: var(--accent); }
a { color: var(--accent); font-weight: 600; }
.card { margin-top: 1.5rem; padding: 1.25rem 1.5rem; border: 1px solid var(--accent); border-radius: 14px; }`;

const FILES: ProjectFile[] = [
  { path: 'index.html', type: 'html', language: 'html', code: INDEX_HTML, url: url('index.html') },
  { path: 'about.html', type: 'html', language: 'html', code: ABOUT_HTML, url: url('about.html') },
  { path: 'styles.css', type: 'other', language: 'css', code: STYLES_CSS, url: url('styles.css') },
];

// The action that reveals the artifact. `id` comes back in the kai-message-action
// detail. Omitting `icon` renders it label-only — a clear text CTA among the
// icon-only built-in actions, rather than another inscrutable glyph.
const OPEN_ACTION = { id: 'open-preview', label: 'Preview', tooltip: 'Open the artifact' };

// The generated artifact shown as a file chip in the message.
const ARTIFACT_ATTACHMENT = {
  id: 'starboard-html',
  type: 'file' as const,
  filename: 'index.html',
  title: 'Starboard landing page',
  mediaType: 'text/html',
};

type CustomAction = { id: string; label: string; icon?: string; tooltip?: string };

interface ChatMsg {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  actions?: (string | CustomAction)[];
  attachments?: Record<string, unknown>[];
}

const SEED_MESSAGES: ChatMsg[] = [
  { id: 'm1', role: 'user', content: 'Build a small landing page for Starboard.' },
  {
    id: 'm2',
    role: 'assistant',
    content:
      "Here's a landing page for Starboard — a hero, a feature card, and an About page sharing one stylesheet. Open the preview to see it rendered, or read the source on the Code tab.",
    attachments: [ARTIFACT_ATTACHMENT],
    actions: [OPEN_ACTION, 'copy'],
  },
];

const REPLY =
  "Updated the page. Open the preview to see the change rendered live, or switch to the Code tab to read the source. Closing the panel returns the conversation to full width.";

let uid = 0;
const nextId = () => `a${++uid}`;

interface Props {
  height?: string;
}

export default function ArtifactRevealDemo(props: Props) {
  const [open, setOpen] = createSignal(false);

  let outerRef: HTMLElement | undefined;       // kai-resizable (chat | artifact)
  let chatItemRef: HTMLElement | undefined;     // kai-resizable-item (chat)
  let artifactItemRef: HTMLElement | undefined; // kai-resizable-item (artifact, hidden until open)
  let artifactMountRef: HTMLDivElement | undefined;

  let chatEl: (HTMLElement & { messages?: ChatMsg[]; [k: string]: unknown }) | undefined;
  let artifactEl: (HTMLElement & { files?: ProjectFile[]; activeFile?: string; src?: string; tab?: string }) | undefined;

  let timer: number | undefined;
  const theme = () => document.documentElement.dataset.theme ?? 'light';

  // Reveal/collapse the artifact panel by toggling the resizable item's `hidden`
  // attribute — the chat pane flexes to fill when the panel is hidden.
  createEffect(() => {
    artifactItemRef?.toggleAttribute('hidden', !open());
  });

  const onMessageAction = (e: Event) => {
    const detail = (e as CustomEvent).detail as { messageId: string; action: string };
    if (detail?.action === 'open-preview') setOpen(true);
  };

  const onSubmit = (e: Event) => {
    const text = (e as CustomEvent).detail?.value?.trim();
    if (!text || !chatEl) return;
    const aId = nextId();
    chatEl.messages = [
      ...(chatEl.messages ?? []),
      { id: nextId(), role: 'user', content: text },
      { id: aId, role: 'assistant', content: '' },
    ];
    (chatEl as any).loading = true;
    const words = REPLY.split(/(\s+)/);
    let i = 0;
    clearTimeout(timer);
    const tick = () => {
      i += 2;
      const partial = words.slice(0, i).join('');
      const done = i >= words.length;
      chatEl!.messages = (chatEl!.messages ?? []).map((m) =>
        m.id === aId
          ? { ...m, content: partial, ...(done ? { attachments: [ARTIFACT_ATTACHMENT], actions: [OPEN_ACTION, 'copy'] } : {}) }
          : m,
      );
      if (!done) timer = window.setTimeout(tick, 38);
      else (chatEl as any).loading = false;
    };
    timer = window.setTimeout(tick, 240);
  };

  const applyTheme = () => {
    const t = theme();
    chatEl?.setAttribute('theme', t);
    artifactEl?.setAttribute('theme', t);
  };

  onMount(async () => {
    await loadKit();

    // --- kai-chat (always present) ---
    chatEl = document.createElement('kai-chat') as typeof chatEl;
    chatEl!.style.cssText = 'display:block;height:100%;width:100%';
    chatEl!.setAttribute('theme', theme());
    (chatEl as any).chatTitle = 'Assistant';
    (chatEl as any).placeholder = 'Ask for a change…';
    customElements.upgrade(chatEl!);
    chatEl!.messages = SEED_MESSAGES;
    chatEl!.addEventListener('kai-message-action', onMessageAction);
    chatEl!.addEventListener('kai-submit', onSubmit);
    chatItemRef?.appendChild(chatEl!);

    // --- kai-artifact (revealed on demand) ---
    artifactEl = document.createElement('kai-artifact') as typeof artifactEl;
    artifactEl!.style.cssText = 'display:block;height:100%;width:100%';
    artifactEl!.setAttribute('theme', theme());
    artifactEl!.setAttribute('iframe-title', 'Starboard artifact preview');
    artifactEl!.setAttribute('open-in-tab', '');
    // First-party same-origin fixtures — opt into allow-same-origin so in-frame
    // link clicks ("About →") keep the address field + back/forward truthful.
    artifactEl!.setAttribute('sandbox', 'allow-scripts allow-forms allow-same-origin');
    customElements.upgrade(artifactEl!);
    artifactEl!.files = FILES;
    artifactEl!.activeFile = 'index.html';
    artifactEl!.src = url('index.html');
    artifactEl!.tab = 'preview';
    artifactMountRef?.appendChild(artifactEl!);

    if (outerRef) customElements.upgrade(outerRef);
    // The resizable's initial layout reads each item's `size` and ignores the
    // `hidden` attribute set before upgrade — re-assert the collapsed state once
    // it's upgraded so the panel starts closed (the reactive effect then drives
    // open/close from the action button).
    requestAnimationFrame(() => artifactItemRef?.toggleAttribute('hidden', !open()));

    const obs = new MutationObserver(applyTheme);
    obs.observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme'] });

    onCleanup(() => {
      clearTimeout(timer);
      chatEl?.removeEventListener('kai-message-action', onMessageAction);
      chatEl?.removeEventListener('kai-submit', onSubmit);
      obs.disconnect();
    });
  });

  return (
    <div
      class="not-content my-5 overflow-hidden rounded-xl border border-line bg-surface"
      style={{ height: props.height ?? '560px' }}
    >
      {/* @ts-expect-error custom element */}
      <kai-resizable
        ref={(el: HTMLElement) => (outerRef = el)}
        orientation="horizontal"
        style={{ display: 'block', height: '100%' }}
      >
        {/* Chat — fills when the artifact panel is hidden */}
        {/* @ts-expect-error custom element */}
        <kai-resizable-item ref={(el: HTMLElement) => (chatItemRef = el)} min="280px" />

        {/* Artifact panel — hidden until an `open-preview` action fires */}
        {/* @ts-expect-error custom element */}
        <kai-resizable-item ref={(el: HTMLElement) => (artifactItemRef = el)} size="54%" min="360px" hidden>
          <div style={{ display: 'flex', 'flex-direction': 'column', height: '100%' }}>
            <div
              class="flex items-center justify-between border-b border-line bg-surface px-3 py-2"
              style={{ gap: '0.5rem' }}
            >
              <span class="text-sm font-semibold text-ink">Starboard landing page</span>
              <button
                type="button"
                onClick={() => setOpen(false)}
                aria-label="Close preview"
                class="inline-flex h-7 w-7 items-center justify-center rounded-md text-ink/70 hover:bg-line/60 hover:text-ink"
              >
                <IconClose style={{ width: '1rem', height: '1rem' }} />
              </button>
            </div>
            <div ref={(el: HTMLDivElement) => (artifactMountRef = el)} style={{ flex: '1', 'min-height': '0' }} />
          </div>
        </kai-resizable-item>
      </kai-resizable>
    </div>
  );
}
