/** Live demo for the "Artifacts canvas beside chat" example.
 *  A split coding/agent layout: <kc-chat> on the LEFT, and on the RIGHT a
 *  <kc-file-tree> above a <kc-artifact>, all inside a <kc-resizable>.
 *  Selecting a file in the tree loads it into the artifact (Code source +
 *  preview src). Elements are built imperatively so arrays/objects are set as
 *  JS PROPERTIES, and the same-origin fixtures in public/artifact-demo/ frame
 *  live in the preview iframe. */
import { onMount, onCleanup } from 'solid-js';
import { loadKit } from './example/kit';

// Same-origin fixtures served from public/artifact-demo/ — BASE_URL is '/chat'
// in prod and '/chat/' in dev, so normalise the trailing slash.
const base = import.meta.env.BASE_URL.replace(/\/$/, '');
const url = (p: string) => `${base}/artifact-demo/${p}`;

// ArtifactFile / FileTreeFile shape: { path, url?, code?, language?, type? }
interface ProjectFile {
  path: string;
  url?: string;
  code?: string;
  language?: string;
  type?: 'html' | 'image' | 'pdf' | 'other';
}

const INDEX_HTML = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="styles.css" />
    <title>Starboard</title>
  </head>
  <body>
    <h1>Starboard</h1>
    <p>A landing page generated by the assistant, framed live in the artifact preview.</p>
    <div class="card">
      <strong>Ship faster</strong>
      <p>Edit the source in the Code tab, or open it in a new browser tab.</p>
    </div>
    <nav><a href="about.html">About →</a></nav>
  </body>
</html>`;

const ABOUT_HTML = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="styles.css" />
    <title>Starboard — About</title>
  </head>
  <body>
    <h1>About Starboard</h1>
    <p>Built with kitn-chat artifacts — a sandboxed preview paired with the source.</p>
    <nav><a href="index.html">← Home</a></nav>
  </body>
</html>`;

const STYLES_CSS = `:root { --accent: #d6207f; --ink: #1b1b1f; --muted: #56565c; }
body {
  font-family: system-ui, sans-serif;
  max-width: 40rem;
  margin: 0 auto;
  padding: 2.5rem 1.5rem;
  color: var(--ink);
  line-height: 1.6;
}
h1 { color: var(--accent); }
a { color: var(--accent); font-weight: 600; }
.card { margin-top: 1.5rem; padding: 1.25rem 1.5rem; border: 1px solid var(--accent); border-radius: 14px; }`;

const THEME_TS = `import { writable } from './store';

export type Theme = 'light' | 'dark';

const KEY = 'starboard.theme';

export const theme = writable<Theme>(
  (localStorage.getItem(KEY) as Theme) ?? 'light',
);

theme.subscribe((value) => {
  document.documentElement.dataset.theme = value;
  localStorage.setItem(KEY, value);
});`;

const STORE_TS = `export interface Writable<T> {
  get(): T;
  set(value: T): void;
  subscribe(fn: (value: T) => void): () => void;
}

export function writable<T>(initial: T): Writable<T> {
  let value = initial;
  const subscribers = new Set<(value: T) => void>();
  return {
    get: () => value,
    set(next) {
      value = next;
      subscribers.forEach((fn) => fn(value));
    },
    subscribe(fn) {
      subscribers.add(fn);
      fn(value);
      return () => subscribers.delete(fn);
    },
  };
}`;

// The project the agent has scaffolded. HTML/CSS files have a real same-origin
// `url` so the preview iframe frames them live; the .ts files are Code-tab only.
const FILES: ProjectFile[] = [
  { path: 'index.html', type: 'html', language: 'html', code: INDEX_HTML, url: url('index.html') },
  { path: 'about.html', type: 'html', language: 'html', code: ABOUT_HTML, url: url('about.html') },
  { path: 'styles.css', type: 'other', language: 'css', code: STYLES_CSS, url: url('styles.css') },
  { path: 'src/theme.ts', type: 'other', language: 'ts', code: THEME_TS },
  { path: 'src/store.ts', type: 'other', language: 'ts', code: STORE_TS },
];

type ChatMsg = { id: string; role: 'user' | 'assistant'; content: string; actions?: string[] };

const SEED_MESSAGES: ChatMsg[] = [
  { id: 'm1', role: 'user', content: 'Scaffold a small landing page for Starboard with a light/dark theme toggle.' },
  {
    id: 'm2',
    role: 'assistant',
    content:
      'Done — the project is on the right. `index.html` and `about.html` share `styles.css`, and `src/theme.ts` persists the choice in `localStorage` via a tiny `writable` store. Click any file in the tree to open it in the canvas; HTML pages render live in the preview.',
    actions: ['copy', 'like', 'dislike'],
  },
];

const REPLY =
  'Pick a file in the tree on the right and it loads into the artifact canvas. HTML files frame live in the sandboxed preview; switch to the Code tab to read or edit the source. The address bar tracks relative links — click "About →" in the preview to navigate, then use back/forward.';

let uid = 0;
const nextId = () => `a${++uid}`;

interface Props {
  height?: string;
}

export default function ArtifactsCanvasDemo(props: Props) {
  // kc-resizable roots + item wrappers (declarative in JSX)
  let outerRef: HTMLElement | undefined;   // chat | (tree/artifact column)
  let rightRef: HTMLElement | undefined;   // vertical: tree above artifact
  let chatItemRef: HTMLElement | undefined;
  let treeItemRef: HTMLElement | undefined;
  let artifactItemRef: HTMLElement | undefined;

  // The kc-* elements created imperatively (so props are set as JS properties)
  let chatEl: (HTMLElement & { messages?: ChatMsg[]; [k: string]: unknown }) | undefined;
  let treeEl: (HTMLElement & { files?: ProjectFile[]; activeFile?: string }) | undefined;
  let artifactEl: (HTMLElement & { files?: ProjectFile[]; activeFile?: string; src?: string; tab?: string }) | undefined;

  let timer: number | undefined;
  const theme = () => document.documentElement.dataset.theme ?? 'light';

  /** Load a file into the artifact canvas: highlight the tree row, set the
   *  Code source, and (for files with a preview url) navigate the preview. */
  const selectFile = (path: string) => {
    const file = FILES.find((f) => f.path === path);
    if (!file || !artifactEl || !treeEl) return;
    treeEl.activeFile = path;
    artifactEl.activeFile = path;
    if (file.url) {
      artifactEl.src = file.url;
      artifactEl.tab = 'preview';
    } else {
      // code-only file — show the source
      artifactEl.tab = 'code';
    }
  };

  const onSelect = (e: Event) => {
    const path = (e as CustomEvent).detail?.path as string | undefined;
    if (path) selectFile(path);
  };

  const onSubmit = (e: Event) => {
    const text = (e as CustomEvent).detail?.value?.trim();
    if (!text || !chatEl) return;
    const aId = nextId();
    chatEl.messages = [
      ...(chatEl.messages ?? []),
      { id: nextId(), role: 'user' as const, content: text },
      { id: aId, role: 'assistant' as const, content: '' },
    ];
    (chatEl as any).loading = true;
    const words = REPLY.split(/(\s+)/);
    let i = 0;
    clearTimeout(timer);
    const tick = () => {
      i += 2;
      const partial = words.slice(0, i).join('');
      const done = i >= words.length;
      chatEl!.messages = (chatEl!.messages ?? []).map((m) =>
        m.id === aId
          ? { ...m, content: partial, ...(done ? { actions: ['copy', 'like', 'dislike'] } : {}) }
          : m,
      );
      if (!done) timer = window.setTimeout(tick, 38);
      else (chatEl as any).loading = false;
    };
    timer = window.setTimeout(tick, 240);
  };

  const applyTheme = () => {
    const t = theme();
    chatEl?.setAttribute('theme', t);
    treeEl?.setAttribute('theme', t);
    artifactEl?.setAttribute('theme', t);
  };

  onMount(async () => {
    await loadKit();

    // --- kc-chat (left pane) ---
    chatEl = document.createElement('kc-chat') as typeof chatEl;
    chatEl!.style.cssText = 'display:block;height:100%;width:100%';
    chatEl!.setAttribute('theme', theme());
    (chatEl as any).chatTitle = 'Build agent';
    (chatEl as any).placeholder = 'Ask the agent to change the project…';
    customElements.upgrade(chatEl!);
    chatEl!.messages = SEED_MESSAGES;
    chatEl!.addEventListener('kc-submit', onSubmit);
    chatItemRef?.appendChild(chatEl!);

    // --- kc-file-tree (top-right) ---
    treeEl = document.createElement('kc-file-tree') as typeof treeEl;
    treeEl!.style.cssText = 'display:block;height:100%;width:100%';
    treeEl!.setAttribute('theme', theme());
    customElements.upgrade(treeEl!);
    treeEl!.files = FILES;
    treeEl!.activeFile = 'index.html';
    treeEl!.addEventListener('kc-select', onSelect);
    treeItemRef?.appendChild(treeEl!);

    // --- kc-artifact (bottom-right canvas) ---
    artifactEl = document.createElement('kc-artifact') as typeof artifactEl;
    artifactEl!.style.cssText = 'display:block;height:100%;width:100%';
    artifactEl!.setAttribute('theme', theme());
    artifactEl!.setAttribute('iframe-title', 'Starboard artifact preview');
    artifactEl!.setAttribute('open-in-tab', '');
    // Opt into allow-same-origin so the canvas observes in-frame link clicks
    // (e.g. "About →") and keeps the address field + back/forward truthful.
    // Safe here: the fixtures are first-party, same-origin files we ship.
    artifactEl!.setAttribute('sandbox', 'allow-scripts allow-forms allow-same-origin');
    customElements.upgrade(artifactEl!);
    artifactEl!.files = FILES;
    artifactEl!.activeFile = 'index.html';
    artifactEl!.src = url('index.html');
    artifactEl!.tab = 'preview';
    // Keep the standalone tree and the canvas in sync when the user picks a
    // file from the artifact's own Code-tab tree, too.
    artifactEl!.addEventListener('kc-file-select', onSelect);
    artifactItemRef?.appendChild(artifactEl!);

    // Upgrade the resizable roots so they read their light children.
    if (rightRef) customElements.upgrade(rightRef);
    if (outerRef) customElements.upgrade(outerRef);

    const obs = new MutationObserver(applyTheme);
    obs.observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme'] });

    onCleanup(() => {
      clearTimeout(timer);
      chatEl?.removeEventListener('kc-submit', onSubmit);
      treeEl?.removeEventListener('kc-select', onSelect);
      artifactEl?.removeEventListener('kc-file-select', onSelect);
      obs.disconnect();
    });
  });

  return (
    <div
      class="not-content my-5 overflow-hidden rounded-xl border border-line bg-surface"
      style={{ height: props.height ?? '620px' }}
    >
      {/* Outer split: chat | canvas column */}
      {/* @ts-expect-error custom element */}
      <kc-resizable
        ref={(el: HTMLElement) => (outerRef = el)}
        orientation="horizontal"
        style={{ display: 'block', height: '100%' }}
      >
        {/* Left: chat — kc-chat appended imperatively in onMount */}
        {/* @ts-expect-error custom element */}
        <kc-resizable-item
          ref={(el: HTMLElement) => (chatItemRef = el)}
          size="42%"
          min="280px"
        />
        {/* Right: a nested vertical split — file tree above the artifact canvas */}
        {/* @ts-expect-error custom element */}
        <kc-resizable-item min="320px">
          {/* @ts-expect-error custom element */}
          <kc-resizable
            ref={(el: HTMLElement) => (rightRef = el)}
            orientation="vertical"
            style={{ display: 'block', height: '100%' }}
          >
            {/* file tree — kc-file-tree appended imperatively in onMount */}
            {/* @ts-expect-error custom element */}
            <kc-resizable-item
              ref={(el: HTMLElement) => (treeItemRef = el)}
              size="34%"
              min="120px"
              max="60%"
            />
            {/* artifact canvas — kc-artifact appended imperatively in onMount */}
            {/* @ts-expect-error custom element */}
            <kc-resizable-item ref={(el: HTMLElement) => (artifactItemRef = el)} min="200px" />
          </kc-resizable>
        </kc-resizable-item>
      </kc-resizable>
    </div>
  );
}
